languageCode = "zh-cn"
languageName = "Chinese"
displayName = "CN"
isoCode = "zh-cn"
weight = 1
rtl = false

title = "a half fish"
logo = "img/blowfish_logo_transparent.png"
description = "记录生活～"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2022.11.11"

[author]
  name = "a half fish"
  image = "img/blowfish_logo.png"
  headline = "温故而知新～"
  bio = "温故而知新～"
  links = [
    # { twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/WUYUEZONG" },
  ]
