languageCode = "cn"
languageName = "Chinese"
displayName = "CN"
isoCode = "cn"
weight = 1
rtl = false

title = "a half fish"
logo = "img/logo.png"
description = "记录生活～"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"
# dateFormat = "January 2, 2006"

[author]
  name = "a half fish"
  image = "img/logo.png"
  headline = "温故而知新～"
  bio = "温故而知新～"
  links = [
    # { twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/WUYUEZONG" },
  ]
