# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# [[main]]
#   name = "Docs"
#   pageRef = "docs"
#   weight = 10

# [[main]]
#   name = "HOME"
#   pageRef = "/"
#   weight = 20

# [[main]]
#   name = "APP"
#   pageRef = "apps"
#   weight = 30

# [[main]]
#   name = "ABOUT"
#   pageRef = "/"
#   weight = 40

# [[main]]
#   identifier = "github"
#   pre = "github"
#   url = "https://github.com/WUYUEZONG"
#   weight = 50

[[main]]
  identifier = "circle-info"
  pre = "circle-info"
  pageRef = "about"
  # url = "https://twitter.com/burufugu"
  weight = 60


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "标签"
   pageRef = "tags"
   weight = 10

[[footer]]
  name = "博客"
  pageRef = "posts"
  weight = 20

 [[footer]]
   name = "工作"
   pageRef = "works"
   weight = 40

#  [[footer]]
#   name = "Apps"
#   pageRef = "apps"
#   weight = 30



#  [[footer]]
#   name = "iOS"
#   pageRef = "ios"
#   weight = 50

 [[footer]]
  name = "学习"
  pageRef = "study"
  weight = 60

#  [[footer]]
#   name = "关于"
#   pageRef = "about"
#   weight = 70