# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "blowfish" #blowfish , avocado , fire , forest , Princess , Neon , Bloody ,Terminal , Marvel , Autumn , Noir ， Congo , Slate
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""

[header]
  layout = "basic" # valid options: basic, fixed

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/img/iceland.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 10
  showMoreLink = false
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background
  layoutBackgroundBlur = false # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editURL = ""
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true 
  showAuthorsBadges = true 
  showWordCount = false
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background
  showBreadcrumbs = true
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = ["taxonomy","term"]
  # excludedKinds = ["taxonomy"]

[taxonomy]
  showTermCount = true

[firebase]
  apiKey = "AIzaSyCQdYYJsqfcjy2_NypuCRgOJczG9RDZy7A"
  authDomain = "homepage-f82a2.firebaseapp.com"
  projectId = "homepage-f82a2"
  storageBucket = "homepage-f82a2.appspot.com"
  messagingSenderId = "574711004803"
  appId = "1:574711004803:web:c313a1a151521a33c4a5b6"
  measurementId = "G-H6WB2ZNB2J"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
